baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

theme = "terminal"


#[author]
#  name = "Satoshi Fukami"
#  bio = "A student researching computational neuroscience"
#  job = "student"
#  location = "Japan"
#  # Your Gravatar email. Overwrite `author.picture` everywhere in the blog
#  gravatarEmail = "fukami.satoshi760@mail.kyutech.jp"
#
#[params]
#  sidebarBehavior = 2
#  thumbnailImage = true
#  dateFormat = "2025-05-24"
#  thumbnailImagePosition = "left"
#  autoThumbnailImage = true
#  #coverImage = "images/cover.jpg"
#  imageGallery = true
#  hierarchicalCategories = true
#  syntaxHighlighter = 'highlight.js'
#  
#[[menu.main]]
#  weight = 1
#  identifier = "home"
#  name = "Home"
#  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-home\" aria-hidden=\"true\"></i>"
#  url = "/"
#[[menu.main]]
#  weight = 2
#  identifier = "categories"
#  name = "Categories"
#  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-bookmark\" aria-hidden=\"true\"></i>"
#  url = "/categories"
#[[menu.main]]
#  weight = 3
#  identifier = "tags"
#  name = "Tags"
#  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-tags\" aria-hidden=\"true\"></i>"
#  url = "/tags"
#[[menu.main]]
#  weight = 5
#  identifier = "about"
#  name = "About"
#  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-question\" aria-hidden=\"true\"></i>"
#  url = "/#about"
#
#[[menu.links]]
#  weight = 0
#  identifier = "github"
#  name = "GitHub"
#  pre = "<i class=\"sidebar-button-icon fab fa-lg fa-github\" aria-hidden=\"true\"></i>"
#  url = ""
